### ISSUE TITLE
Make experimental scope with the two BluRay lenses

### ISSUE THREAD

**Issue by gvJaime** [gvJaime/microspot#66]

**Comment by elgambitero** [comment]
Refractive indices are needed for proper calculation.

**Comment by elgambitero** [comment]
In case of not having proper index measurements, consider making a focusing mechanism, modifying the distance between the two lenses.

**Comment by gvJaime** [comment]
This issue has been obsoleted by the preference of stock lenses, and the new "Snell law" command.

Version 0.3 issue #180 already counts on this.
